name: shelf_throttle
description: A Shelf middleware that applies throttling to incoming requests.
version: 0.5.1
homepage: https://github.com/tomwyr/shelf-throttle

environment:
  sdk: ^3.3.0

dependencies:
  shelf: ^1.4.1

dev_dependencies:
  fake_async: ^1.3.1
  lints: ^3.0.0
  meta: ^1.12.0
  mocktail: ^1.0.3
  test: ^1.24.0
  time: ^2.1.4
